name: Replace placeholders

on:
  release:
    types: [published]
  workflow_dispatch: # Allow manual trigger

jobs:
  replace:
    runs-on: ubuntu-latest
    name: Replace Placeholders in File.

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/readme-replacer@main
        with:
          CUSTOM_REPLACER_FILE: "./.github/customReplacer.json"
